global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "ndiscord-server"
    static_configs:
      - targets: ["server:9100"]
        labels:
          service: "ndiscord"

  - job_name: "livekit"
    static_configs:
      - targets: ["livekit:6789"]
        labels:
          service: "livekit"
