// Code generated by FlashORM. DO NOT EDIT.

package flash_gen

import (
	"context"

	"github.com/apache/cassandra-gocql-driver/v2"
)

type DBTX interface {
	Query(stmt string, values ...interface{}) *gocql.Query
}

func Newq(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) exec(ctx context.Context, query string, args ...interface{}) error {
	return q.db.Query(query, args...).ExecContext(ctx)
}
