// Code generated by FlashORM. DO NOT EDIT.

package flash_gen

import (
	"context"
	"time"
)

type CreatemessageParams struct {
	ChannelId              string    `json:"channel_id"`
	Id                     string    `json:"id"`
	AuthorId               string    `json:"author_id"`
	Content                string    `json:"content"`
	Type                   int64     `json:"type_"`
	ReplyToId              string    `json:"reply_to_id"`
	Pinned                 bool      `json:"pinned"`
	CreatedAt              time.Time `json:"created_at"`
	ForwardedFromChannelId string    `json:"forwarded_from_channel_id"`
	ForwardedFromMessageId string    `json:"forwarded_from_message_id"`
	ForwardedFromAuthorId  string    `json:"forwarded_from_author_id"`
	MentionUserIds         []string  `json:"mention_user_ids"`
}

func (q *Queries) Createmessage(ctx context.Context, arg CreatemessageParams) error {
	const query = `INSERT INTO ndiscord.messages ( channel_id, id, author_id, content, type, reply_to_id, pinned, created_at, forwarded_from_channel_id, forwarded_from_message_id, forwarded_from_author_id, mention_user_ids ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);`
	args := []interface{}{arg.ChannelId, arg.Id, arg.AuthorId, arg.Content, arg.Type, arg.ReplyToId, arg.Pinned, arg.CreatedAt, arg.ForwardedFromChannelId, arg.ForwardedFromMessageId, arg.ForwardedFromAuthorId, arg.MentionUserIds}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Getmessage(ctx context.Context, channel_id string, id string) (GetmessageRow, error) {
	const query = `SELECT channel_id, id, author_id, content, type, reply_to_id, pinned, edited_at, created_at, deleted, updated_at, forwarded_from_channel_id, forwarded_from_message_id, forwarded_from_author_id, mention_user_ids FROM ndiscord.messages WHERE channel_id = ? AND id = ?;`
	args := []interface{}{channel_id, id}

	var result GetmessageRow
	err := q.db.Query(query, args...).WithContext(ctx).Scan(
		&result.ChannelId,
		&result.Id,
		&result.AuthorId,
		&result.Content,
		&result.Type,
		&result.ReplyToId,
		&result.Pinned,
		&result.EditedAt,
		&result.CreatedAt,
		&result.Deleted,
		&result.UpdatedAt,
		&result.ForwardedFromChannelId,
		&result.ForwardedFromMessageId,
		&result.ForwardedFromAuthorId,
		&result.MentionUserIds,
	)
	if err != nil {
		return result, err
	}
	return result, nil
}

type GetmessageRow struct {
	ChannelId              string    `json:"channel_id"`
	Id                     string    `json:"id"`
	AuthorId               string    `json:"author_id"`
	Content                string    `json:"content"`
	Type                   int64     `json:"type"`
	ReplyToId              string    `json:"reply_to_id"`
	Pinned                 bool      `json:"pinned"`
	EditedAt               time.Time `json:"edited_at"`
	CreatedAt              time.Time `json:"created_at"`
	Deleted                bool      `json:"deleted"`
	UpdatedAt              time.Time `json:"updated_at"`
	ForwardedFromChannelId string    `json:"forwarded_from_channel_id"`
	ForwardedFromMessageId string    `json:"forwarded_from_message_id"`
	ForwardedFromAuthorId  string    `json:"forwarded_from_author_id"`
	MentionUserIds         []string  `json:"mention_user_ids"`
}

type UpdatemessagecontentParams struct {
	Content   string    `json:"content"`
	EditedAt  time.Time `json:"edited_at"`
	ChannelId string    `json:"channel_id"`
	Id        string    `json:"id"`
}

func (q *Queries) Updatemessagecontent(ctx context.Context, arg UpdatemessagecontentParams) error {
	const query = `UPDATE ndiscord.messages SET content = ?, edited_at = ? WHERE channel_id = ? AND id = ?;`
	args := []interface{}{arg.Content, arg.EditedAt, arg.ChannelId, arg.Id}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Deletemessage(ctx context.Context, updated_at time.Time, channel_id string, id string) error {
	const query = `UPDATE ndiscord.messages SET deleted = true, updated_at = ? WHERE channel_id = ? AND id = ?;`
	args := []interface{}{updated_at, channel_id, id}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Listmessagesbefore(ctx context.Context, channel_id string, param2 string, limit string) ([]ListmessagesbeforeRow, error) {
	const query = `SELECT channel_id, id, author_id, content, type, reply_to_id, pinned, edited_at, created_at, deleted, updated_at, forwarded_from_channel_id, forwarded_from_message_id, forwarded_from_author_id, mention_user_ids FROM ndiscord.messages WHERE channel_id = ? AND id < ? ORDER BY id DESC LIMIT ?;`
	args := []interface{}{channel_id, param2, limit}

	var items []ListmessagesbeforeRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item ListmessagesbeforeRow
	for iter.Scan(
		&item.ChannelId,
		&item.Id,
		&item.AuthorId,
		&item.Content,
		&item.Type,
		&item.ReplyToId,
		&item.Pinned,
		&item.EditedAt,
		&item.CreatedAt,
		&item.Deleted,
		&item.UpdatedAt,
		&item.ForwardedFromChannelId,
		&item.ForwardedFromMessageId,
		&item.ForwardedFromAuthorId,
		&item.MentionUserIds,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type ListmessagesbeforeRow struct {
	ChannelId              string    `json:"channel_id"`
	Id                     string    `json:"id"`
	AuthorId               string    `json:"author_id"`
	Content                string    `json:"content"`
	Type                   int64     `json:"type"`
	ReplyToId              string    `json:"reply_to_id"`
	Pinned                 bool      `json:"pinned"`
	EditedAt               time.Time `json:"edited_at"`
	CreatedAt              time.Time `json:"created_at"`
	Deleted                bool      `json:"deleted"`
	UpdatedAt              time.Time `json:"updated_at"`
	ForwardedFromChannelId string    `json:"forwarded_from_channel_id"`
	ForwardedFromMessageId string    `json:"forwarded_from_message_id"`
	ForwardedFromAuthorId  string    `json:"forwarded_from_author_id"`
	MentionUserIds         []string  `json:"mention_user_ids"`
}

func (q *Queries) Listmessagesafter(ctx context.Context, channel_id string, param2 string, limit string) ([]ListmessagesafterRow, error) {
	const query = `SELECT channel_id, id, author_id, content, type, reply_to_id, pinned, edited_at, created_at, deleted, updated_at, forwarded_from_channel_id, forwarded_from_message_id, forwarded_from_author_id, mention_user_ids FROM ndiscord.messages WHERE channel_id = ? AND id > ? ORDER BY id ASC LIMIT ?;`
	args := []interface{}{channel_id, param2, limit}

	var items []ListmessagesafterRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item ListmessagesafterRow
	for iter.Scan(
		&item.ChannelId,
		&item.Id,
		&item.AuthorId,
		&item.Content,
		&item.Type,
		&item.ReplyToId,
		&item.Pinned,
		&item.EditedAt,
		&item.CreatedAt,
		&item.Deleted,
		&item.UpdatedAt,
		&item.ForwardedFromChannelId,
		&item.ForwardedFromMessageId,
		&item.ForwardedFromAuthorId,
		&item.MentionUserIds,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type ListmessagesafterRow struct {
	ChannelId              string    `json:"channel_id"`
	Id                     string    `json:"id"`
	AuthorId               string    `json:"author_id"`
	Content                string    `json:"content"`
	Type                   int64     `json:"type"`
	ReplyToId              string    `json:"reply_to_id"`
	Pinned                 bool      `json:"pinned"`
	EditedAt               time.Time `json:"edited_at"`
	CreatedAt              time.Time `json:"created_at"`
	Deleted                bool      `json:"deleted"`
	UpdatedAt              time.Time `json:"updated_at"`
	ForwardedFromChannelId string    `json:"forwarded_from_channel_id"`
	ForwardedFromMessageId string    `json:"forwarded_from_message_id"`
	ForwardedFromAuthorId  string    `json:"forwarded_from_author_id"`
	MentionUserIds         []string  `json:"mention_user_ids"`
}

func (q *Queries) Listrecentmessages(ctx context.Context, channel_id string, limit string) ([]ListrecentmessagesRow, error) {
	const query = `SELECT channel_id, id, author_id, content, type, reply_to_id, pinned, edited_at, created_at, deleted, updated_at, forwarded_from_channel_id, forwarded_from_message_id, forwarded_from_author_id, mention_user_ids FROM ndiscord.messages WHERE channel_id = ? ORDER BY id DESC LIMIT ?;`
	args := []interface{}{channel_id, limit}

	var items []ListrecentmessagesRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item ListrecentmessagesRow
	for iter.Scan(
		&item.ChannelId,
		&item.Id,
		&item.AuthorId,
		&item.Content,
		&item.Type,
		&item.ReplyToId,
		&item.Pinned,
		&item.EditedAt,
		&item.CreatedAt,
		&item.Deleted,
		&item.UpdatedAt,
		&item.ForwardedFromChannelId,
		&item.ForwardedFromMessageId,
		&item.ForwardedFromAuthorId,
		&item.MentionUserIds,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type ListrecentmessagesRow struct {
	ChannelId              string    `json:"channel_id"`
	Id                     string    `json:"id"`
	AuthorId               string    `json:"author_id"`
	Content                string    `json:"content"`
	Type                   int64     `json:"type"`
	ReplyToId              string    `json:"reply_to_id"`
	Pinned                 bool      `json:"pinned"`
	EditedAt               time.Time `json:"edited_at"`
	CreatedAt              time.Time `json:"created_at"`
	Deleted                bool      `json:"deleted"`
	UpdatedAt              time.Time `json:"updated_at"`
	ForwardedFromChannelId string    `json:"forwarded_from_channel_id"`
	ForwardedFromMessageId string    `json:"forwarded_from_message_id"`
	ForwardedFromAuthorId  string    `json:"forwarded_from_author_id"`
	MentionUserIds         []string  `json:"mention_user_ids"`
}

func (q *Queries) Setpinned(ctx context.Context, pinned bool, channel_id string, id string) error {
	const query = `UPDATE ndiscord.messages SET pinned = ? WHERE channel_id = ? AND id = ?;`
	args := []interface{}{pinned, channel_id, id}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Getmessagessince(ctx context.Context, channel_id string, param2 string) ([]GetmessagessinceRow, error) {
	const query = `SELECT channel_id, id, author_id, content, type, reply_to_id, pinned, edited_at, created_at, deleted, updated_at, forwarded_from_channel_id, forwarded_from_message_id, forwarded_from_author_id, mention_user_ids FROM ndiscord.messages WHERE channel_id = ? AND updated_at > ? ALLOW FILTERING;`
	args := []interface{}{channel_id, param2}

	var items []GetmessagessinceRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item GetmessagessinceRow
	for iter.Scan(
		&item.ChannelId,
		&item.Id,
		&item.AuthorId,
		&item.Content,
		&item.Type,
		&item.ReplyToId,
		&item.Pinned,
		&item.EditedAt,
		&item.CreatedAt,
		&item.Deleted,
		&item.UpdatedAt,
		&item.ForwardedFromChannelId,
		&item.ForwardedFromMessageId,
		&item.ForwardedFromAuthorId,
		&item.MentionUserIds,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type GetmessagessinceRow struct {
	ChannelId              string    `json:"channel_id"`
	Id                     string    `json:"id"`
	AuthorId               string    `json:"author_id"`
	Content                string    `json:"content"`
	Type                   int64     `json:"type"`
	ReplyToId              string    `json:"reply_to_id"`
	Pinned                 bool      `json:"pinned"`
	EditedAt               time.Time `json:"edited_at"`
	CreatedAt              time.Time `json:"created_at"`
	Deleted                bool      `json:"deleted"`
	UpdatedAt              time.Time `json:"updated_at"`
	ForwardedFromChannelId string    `json:"forwarded_from_channel_id"`
	ForwardedFromMessageId string    `json:"forwarded_from_message_id"`
	ForwardedFromAuthorId  string    `json:"forwarded_from_author_id"`
	MentionUserIds         []string  `json:"mention_user_ids"`
}

type AddmessageattachmentParams struct {
	ChannelId   string `json:"channel_id"`
	MessageId   string `json:"message_id"`
	Id          string `json:"id"`
	Filename    string `json:"filename"`
	Url         string `json:"url"`
	ContentType string `json:"content_type"`
	Size        int64  `json:"size"`
}

func (q *Queries) Addmessageattachment(ctx context.Context, arg AddmessageattachmentParams) error {
	const query = `INSERT INTO ndiscord.message_attachments ( channel_id, message_id, id, filename, url, content_type, size ) VALUES (?, ?, ?, ?, ?, ?, ?);`
	args := []interface{}{arg.ChannelId, arg.MessageId, arg.Id, arg.Filename, arg.Url, arg.ContentType, arg.Size}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Getmessageattachments(ctx context.Context, channel_id string, message_id string) ([]GetmessageattachmentsRow, error) {
	const query = `SELECT id, filename, url, content_type, size FROM ndiscord.message_attachments WHERE channel_id = ? AND message_id = ?;`
	args := []interface{}{channel_id, message_id}

	var items []GetmessageattachmentsRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item GetmessageattachmentsRow
	for iter.Scan(
		&item.Id,
		&item.Filename,
		&item.Url,
		&item.ContentType,
		&item.Size,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type GetmessageattachmentsRow struct {
	Id          string `json:"id"`
	Filename    string `json:"filename"`
	Url         string `json:"url"`
	ContentType string `json:"content_type"`
	Size        int64  `json:"size"`
}

func (q *Queries) Deletemessageattachments(ctx context.Context, channel_id string, message_id string) error {
	const query = `DELETE FROM ndiscord.message_attachments WHERE channel_id = ? AND message_id = ?;`
	args := []interface{}{channel_id, message_id}

	return q.exec(ctx, query, args...)
}

type AddreactionParams struct {
	ChannelId string `json:"channel_id"`
	MessageId string `json:"message_id"`
	Emoji     string `json:"emoji"`
	UserId    string `json:"user_id"`
}

func (q *Queries) Addreaction(ctx context.Context, arg AddreactionParams) error {
	const query = `INSERT INTO ndiscord.message_reactions ( channel_id, message_id, emoji, user_id ) VALUES (?, ?, ?, ?);`
	args := []interface{}{arg.ChannelId, arg.MessageId, arg.Emoji, arg.UserId}

	return q.exec(ctx, query, args...)
}

type RemovereactionParams struct {
	ChannelId string `json:"channel_id"`
	MessageId string `json:"message_id"`
	Emoji     string `json:"emoji"`
	UserId    string `json:"user_id"`
}

func (q *Queries) Removereaction(ctx context.Context, arg RemovereactionParams) error {
	const query = `DELETE FROM ndiscord.message_reactions WHERE channel_id = ? AND message_id = ? AND emoji = ? AND user_id = ?;`
	args := []interface{}{arg.ChannelId, arg.MessageId, arg.Emoji, arg.UserId}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Getreactions(ctx context.Context, channel_id string, message_id string) ([]GetreactionsRow, error) {
	const query = `SELECT emoji, user_id FROM ndiscord.message_reactions WHERE channel_id = ? AND message_id = ?;`
	args := []interface{}{channel_id, message_id}

	var items []GetreactionsRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item GetreactionsRow
	for iter.Scan(
		&item.Emoji,
		&item.UserId,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type GetreactionsRow struct {
	Emoji  string `json:"emoji"`
	UserId string `json:"user_id"`
}

func (q *Queries) Deletemessagereactions(ctx context.Context, channel_id string, message_id string) error {
	const query = `DELETE FROM ndiscord.message_reactions WHERE channel_id = ? AND message_id = ?;`
	args := []interface{}{channel_id, message_id}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Getreadstate(ctx context.Context, user_id string, channel_id string) (GetreadstateRow, error) {
	const query = `SELECT mention_count, last_read_message_id FROM ndiscord.read_states WHERE user_id = ? AND channel_id = ?;`
	args := []interface{}{user_id, channel_id}

	var result GetreadstateRow
	err := q.db.Query(query, args...).WithContext(ctx).Scan(
		&result.MentionCount,
		&result.LastReadMessageId,
	)
	if err != nil {
		return result, err
	}
	return result, nil
}

type GetreadstateRow struct {
	MentionCount      int64  `json:"mention_count"`
	LastReadMessageId string `json:"last_read_message_id"`
}

type UpsertreadstateParams struct {
	UserId            string `json:"user_id"`
	ChannelId         string `json:"channel_id"`
	LastReadMessageId string `json:"last_read_message_id"`
	MentionCount      int64  `json:"mention_count"`
}

func (q *Queries) Upsertreadstate(ctx context.Context, arg UpsertreadstateParams) error {
	const query = `INSERT INTO ndiscord.read_states ( user_id, channel_id, last_read_message_id, mention_count ) VALUES (?, ?, ?, ?);`
	args := []interface{}{arg.UserId, arg.ChannelId, arg.LastReadMessageId, arg.MentionCount}

	return q.exec(ctx, query, args...)
}

type IncrementmentioncountParams struct {
	UserId            string `json:"user_id"`
	ChannelId         string `json:"channel_id"`
	LastReadMessageId string `json:"last_read_message_id"`
	MentionCount      int64  `json:"mention_count"`
}

func (q *Queries) Incrementmentioncount(ctx context.Context, arg IncrementmentioncountParams) error {
	const query = `INSERT INTO ndiscord.read_states ( user_id, channel_id, last_read_message_id, mention_count ) VALUES (?, ?, ?, ?);`
	args := []interface{}{arg.UserId, arg.ChannelId, arg.LastReadMessageId, arg.MentionCount}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Getuserreadstates(ctx context.Context, user_id string) ([]GetuserreadstatesRow, error) {
	const query = `SELECT user_id, channel_id, last_read_message_id, mention_count FROM ndiscord.read_states WHERE user_id = ?;`
	args := []interface{}{user_id}

	var items []GetuserreadstatesRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item GetuserreadstatesRow
	for iter.Scan(
		&item.UserId,
		&item.ChannelId,
		&item.LastReadMessageId,
		&item.MentionCount,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type GetuserreadstatesRow struct {
	UserId            string `json:"user_id"`
	ChannelId         string `json:"channel_id"`
	LastReadMessageId string `json:"last_read_message_id"`
	MentionCount      int64  `json:"mention_count"`
}

func (q *Queries) Countunreadmessages(ctx context.Context, channel_id string, param2 string) ([]CountunreadmessagesRow, error) {
	const query = `SELECT id, created_at, deleted FROM ndiscord.messages WHERE channel_id = ? AND id > ? ORDER BY id DESC;`
	args := []interface{}{channel_id, param2}

	var items []CountunreadmessagesRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item CountunreadmessagesRow
	for iter.Scan(
		&item.Id,
		&item.CreatedAt,
		&item.Deleted,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type CountunreadmessagesRow struct {
	Id        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Deleted   bool      `json:"deleted"`
}

func (q *Queries) Countallmessages(ctx context.Context, channel_id string) ([]CountallmessagesRow, error) {
	const query = `SELECT id, created_at, deleted FROM ndiscord.messages WHERE channel_id = ? ORDER BY id DESC;`
	args := []interface{}{channel_id}

	var items []CountallmessagesRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item CountallmessagesRow
	for iter.Scan(
		&item.Id,
		&item.CreatedAt,
		&item.Deleted,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type CountallmessagesRow struct {
	Id        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Deleted   bool      `json:"deleted"`
}

type SaveedithistoryParams struct {
	ChannelId  string    `json:"channel_id"`
	MessageId  string    `json:"message_id"`
	OldContent string    `json:"old_content"`
	EditedAt   time.Time `json:"edited_at"`
}

func (q *Queries) Saveedithistory(ctx context.Context, arg SaveedithistoryParams) error {
	const query = `INSERT INTO ndiscord.message_edit_history ( channel_id, message_id, old_content, edited_at ) VALUES (?, ?, ?, ?);`
	args := []interface{}{arg.ChannelId, arg.MessageId, arg.OldContent, arg.EditedAt}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Getedithistory(ctx context.Context, channel_id string, message_id string) ([]GetedithistoryRow, error) {
	const query = `SELECT channel_id, message_id, old_content, edited_at FROM ndiscord.message_edit_history WHERE channel_id = ? AND message_id = ? ORDER BY edited_at DESC;`
	args := []interface{}{channel_id, message_id}

	var items []GetedithistoryRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item GetedithistoryRow
	for iter.Scan(
		&item.ChannelId,
		&item.MessageId,
		&item.OldContent,
		&item.EditedAt,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type GetedithistoryRow struct {
	ChannelId  string    `json:"channel_id"`
	MessageId  string    `json:"message_id"`
	OldContent string    `json:"old_content"`
	EditedAt   time.Time `json:"edited_at"`
}

func (q *Queries) Deleteedithistory(ctx context.Context, channel_id string, message_id string) error {
	const query = `DELETE FROM ndiscord.message_edit_history WHERE channel_id = ? AND message_id = ?;`
	args := []interface{}{channel_id, message_id}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Searchmessagessource(ctx context.Context, channel_id string, limit string) ([]SearchmessagessourceRow, error) {
	const query = `SELECT channel_id, id, author_id, content, type, reply_to_id, pinned, edited_at, created_at, deleted, updated_at, forwarded_from_channel_id, forwarded_from_message_id, forwarded_from_author_id, mention_user_ids FROM ndiscord.messages WHERE channel_id = ? ORDER BY id DESC LIMIT ?;`
	args := []interface{}{channel_id, limit}

	var items []SearchmessagessourceRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item SearchmessagessourceRow
	for iter.Scan(
		&item.ChannelId,
		&item.Id,
		&item.AuthorId,
		&item.Content,
		&item.Type,
		&item.ReplyToId,
		&item.Pinned,
		&item.EditedAt,
		&item.CreatedAt,
		&item.Deleted,
		&item.UpdatedAt,
		&item.ForwardedFromChannelId,
		&item.ForwardedFromMessageId,
		&item.ForwardedFromAuthorId,
		&item.MentionUserIds,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type SearchmessagessourceRow struct {
	ChannelId              string    `json:"channel_id"`
	Id                     string    `json:"id"`
	AuthorId               string    `json:"author_id"`
	Content                string    `json:"content"`
	Type                   int64     `json:"type"`
	ReplyToId              string    `json:"reply_to_id"`
	Pinned                 bool      `json:"pinned"`
	EditedAt               time.Time `json:"edited_at"`
	CreatedAt              time.Time `json:"created_at"`
	Deleted                bool      `json:"deleted"`
	UpdatedAt              time.Time `json:"updated_at"`
	ForwardedFromChannelId string    `json:"forwarded_from_channel_id"`
	ForwardedFromMessageId string    `json:"forwarded_from_message_id"`
	ForwardedFromAuthorId  string    `json:"forwarded_from_author_id"`
	MentionUserIds         []string  `json:"mention_user_ids"`
}

func (q *Queries) Getthreadmessagessource(ctx context.Context, channel_id string, limit string) ([]GetthreadmessagessourceRow, error) {
	const query = `SELECT channel_id, id, author_id, content, type, reply_to_id, pinned, edited_at, created_at, deleted, updated_at, forwarded_from_channel_id, forwarded_from_message_id, forwarded_from_author_id, mention_user_ids FROM ndiscord.messages WHERE channel_id = ? ORDER BY id DESC LIMIT ?;`
	args := []interface{}{channel_id, limit}

	var items []GetthreadmessagessourceRow
	iter := q.db.Query(query, args...).WithContext(ctx).Iter()
	var item GetthreadmessagessourceRow
	for iter.Scan(
		&item.ChannelId,
		&item.Id,
		&item.AuthorId,
		&item.Content,
		&item.Type,
		&item.ReplyToId,
		&item.Pinned,
		&item.EditedAt,
		&item.CreatedAt,
		&item.Deleted,
		&item.UpdatedAt,
		&item.ForwardedFromChannelId,
		&item.ForwardedFromMessageId,
		&item.ForwardedFromAuthorId,
		&item.MentionUserIds,
	) {
		items = append(items, item)
	}
	return items, iter.Close()
}

type GetthreadmessagessourceRow struct {
	ChannelId              string    `json:"channel_id"`
	Id                     string    `json:"id"`
	AuthorId               string    `json:"author_id"`
	Content                string    `json:"content"`
	Type                   int64     `json:"type"`
	ReplyToId              string    `json:"reply_to_id"`
	Pinned                 bool      `json:"pinned"`
	EditedAt               time.Time `json:"edited_at"`
	CreatedAt              time.Time `json:"created_at"`
	Deleted                bool      `json:"deleted"`
	UpdatedAt              time.Time `json:"updated_at"`
	ForwardedFromChannelId string    `json:"forwarded_from_channel_id"`
	ForwardedFromMessageId string    `json:"forwarded_from_message_id"`
	ForwardedFromAuthorId  string    `json:"forwarded_from_author_id"`
	MentionUserIds         []string  `json:"mention_user_ids"`
}

func (q *Queries) Deletemessageattachmentscascade(ctx context.Context, channel_id string, message_id string) error {
	const query = `DELETE FROM ndiscord.message_attachments WHERE channel_id = ? AND message_id = ?;`
	args := []interface{}{channel_id, message_id}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Deletemessagereactionscascade(ctx context.Context, channel_id string, message_id string) error {
	const query = `DELETE FROM ndiscord.message_reactions WHERE channel_id = ? AND message_id = ?;`
	args := []interface{}{channel_id, message_id}

	return q.exec(ctx, query, args...)
}

func (q *Queries) Deletemessageedithistorycascade(ctx context.Context, channel_id string, message_id string) error {
	const query = `DELETE FROM ndiscord.message_edit_history WHERE channel_id = ? AND message_id = ?;`
	args := []interface{}{channel_id, message_id}

	return q.exec(ctx, query, args...)
}
