// Code generated by FlashORM. DO NOT EDIT.

package flash_gen

import (
	"time"
)

type NdiscordMessages struct {
	ChannelId              *string    `json:"channel_id" db:"channel_id"`
	Id                     *string    `json:"id" db:"id"`
	AuthorId               *string    `json:"author_id" db:"author_id"`
	Content                *string    `json:"content" db:"content"`
	Type                   *int64     `json:"type" db:"type"`
	ReplyToId              *string    `json:"reply_to_id" db:"reply_to_id"`
	Pinned                 *bool      `json:"pinned" db:"pinned"`
	Deleted                *bool      `json:"deleted" db:"deleted"`
	EditedAt               *time.Time `json:"edited_at" db:"edited_at"`
	UpdatedAt              *time.Time `json:"updated_at" db:"updated_at"`
	CreatedAt              *time.Time `json:"created_at" db:"created_at"`
	ForwardedFromChannelId *string    `json:"forwarded_from_channel_id" db:"forwarded_from_channel_id"`
	ForwardedFromMessageId *string    `json:"forwarded_from_message_id" db:"forwarded_from_message_id"`
	ForwardedFromAuthorId  *string    `json:"forwarded_from_author_id" db:"forwarded_from_author_id"`
	MentionUserIds         *[]string  `json:"mention_user_ids" db:"mention_user_ids"`
}

type NdiscordMessageAttachments struct {
	ChannelId   *string `json:"channel_id" db:"channel_id"`
	MessageId   *string `json:"message_id" db:"message_id"`
	Id          *string `json:"id" db:"id"`
	Filename    *string `json:"filename" db:"filename"`
	Url         *string `json:"url" db:"url"`
	ContentType *string `json:"content_type" db:"content_type"`
	Size        *int64  `json:"size" db:"size"`
}

type NdiscordMessageReactions struct {
	ChannelId *string `json:"channel_id" db:"channel_id"`
	MessageId *string `json:"message_id" db:"message_id"`
	Emoji     *string `json:"emoji" db:"emoji"`
	UserId    *string `json:"user_id" db:"user_id"`
}

type NdiscordReadStates struct {
	UserId            *string `json:"user_id" db:"user_id"`
	ChannelId         *string `json:"channel_id" db:"channel_id"`
	LastReadMessageId *string `json:"last_read_message_id" db:"last_read_message_id"`
	MentionCount      *int64  `json:"mention_count" db:"mention_count"`
}

type NdiscordAuditLog struct {
	GuildId    *string    `json:"guild_id" db:"guild_id"`
	Id         *string    `json:"id" db:"id"`
	ActionType *int64     `json:"action_type" db:"action_type"`
	UserId     *string    `json:"user_id" db:"user_id"`
	TargetId   *string    `json:"target_id" db:"target_id"`
	Changes    *string    `json:"changes" db:"changes"`
	CreatedAt  *time.Time `json:"created_at" db:"created_at"`
}

type NdiscordMessageEditHistory struct {
	ChannelId  *string    `json:"channel_id" db:"channel_id"`
	MessageId  *string    `json:"message_id" db:"message_id"`
	OldContent *string    `json:"old_content" db:"old_content"`
	EditedAt   *time.Time `json:"edited_at" db:"edited_at"`
}
